version: '3.8'

services:
  easylaw-streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TESSDATA_PREFIX=/usr/share/tessdata
      - PYTHONUNBUFFERED=1
    volumes:
      - ./chroma_db:/app/chroma_db
    networks:
      - easylaw-network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - easylaw-network
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull gemma3:12b &&
        wait
      "

volumes:
  ollama_data:

networks:
  easylaw-network:
    driver: bridge 