services:
  easylaw:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-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}
      - TESSDATA_PREFIX=/usr/share/tessdata
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 